[package]
name = "bloom_filter"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"
license = "MIT"

[features]
std = []
default = ["std"]

[dependencies]
bit-vec = "0.5.0"

[dev-dependencies]
hashers = "1.0.1"
murmur3 = "0.4.1"
